### ISSUE TITLE
Invitation to "boot" participates on Chat not-under-my-control

### ISSUE THREAD

**Issue by Romaq** [viocost/islands#7]
Under the "Settings" tab with "Participants" selected, I am invited to boot any and all participants. Attempting to boot Otter from his own chat, I have "Participant booting failed: Not enough rights to boot a member". I asked Otter permission before attempting, and of course it failed. He suggested I shouldn't be invited to do that which I have no rights to do. I did not attempt to boot anyone else, as I did not have permission to do so.

**Comment by viocost** [comment]
Fixed in version 1.0.0
